### PR TITLE
feat: fall back to lua version from installed version

### LINKED ISSUE #213: [QOL] If `--lua-version` is not set, get it from the installed lua version
We can parse the Lua version using the command `lua -v`.

### PR DESCRIPTION
**Pull request by mrcjkb**
Closes #213.

### CODE REVIEW

**Review by max397574 — APPROVED** [review]

**Review by vhyrro — APPROVED** [review]

**Comment by mrcjkb** [comment]
Something seems broken

**Comment by mrcjkb** [comment]
The `pull_manifest` tests are flaky again.

**Comment by mrcjkb** [comment]
Removed some entries from our test manifest

**Comment by vhyrro** [comment]
Looks like there's a failure with the mock server.

**Pull request merged**
